### ISSUE TITLE
js files in subfolders are ignored

### ISSUE THREAD

**Issue by ericossj** [blutorange/closure-compiler-maven-plugin#60]
![image](https://user-images.githubusercontent.com/71427011/193470812-b376267d-a4ea-45d7-a3f1-3f4108a44d80.png)

![image](https://user-images.githubusercontent.com/71427011/193471034-043776d8-b7fa-49db-b82a-58b2e4d9da24.png)

**Comment by blutorange** [comment]
Hmm, I'll need to take a look, but just to make sure, what you mean is, the file `GridColunaSubTabela.js` should be included in the bundle as well, but currently it is not?

**Comment by ericossj** [comment]
thanks for the reply blutorange, exactly, the content of the file is not included in the minified

**Comment by blutorange** [comment]
So yesterday was a national holiday here in Germany, but today I've got some time to take a look at this.

I tried to reproduce what you described, but as far as I can tell, everything is working as intended. However, please note:

* The docs for `bundleConfiguration` say `If not an absolute path, it must be relative to the project base directory.`. But in your screenshot, you specify `/minify.json`. This is an absolute path in Linux, but not in Windows, so I'm assuming you are running on a Windows system (otherwise the build should fail). Nonetheless, I would recommend you omit the slash for cross-platform builds.
*  The base directory for the files specified in the bundle is taken from the `baseSourceDir` / `sourceDir` property. Since you did not specify that property in the plugin configuration, `baseSourceDir` defaults to `${basedir}/src/main/webapp`. (It could be argued that it would make more sense that file paths should be relative to the bundle JSON file location, but that's how it is and I cannot change that for compatibility)

Here's a minimal Maven project based on the screenshot you posted that works, both files are included in the minified file: https://filebin.net/1ls51dx1vsc5kb48

If that doesn't solve your issue, can you make a sample project that illustrates the error?

PS: The JSON bundle feature still exists because I took it from the project from which this one was forked, but tbh, I don't quite see the point of JSON bundle files. Is there any particular reason you prefer a JSON file with the files to include instead of just configuring everything in the `pom.xml` (using multiple executions if you need multiple bundles)?

**Comment by ericossj** [comment]
Good evening, sorry for the delay in responding.
First I would like to apologize because it was my mistake,
as the problem was in the name of the folder "subTabela" in the capital letter "T".
I changed the name correctly and it solved my problem.

Anyway, I'd like to thank you for the feedback.
